# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  Example: 'paul'

steps:
- task: Bash@3
  inputs:
    filePath: 'azureProvision.sh'
    arguments: 'HiThereFred'

- script: echo This is the source dir $(Build.SourcesDirectory)

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Visual Studio Enterprise(53db002d-ccb5-4326-a6d3-0057195581cc)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'azureCommands.sh'

- task: SSH@0
  inputs:
    sshEndpoint: 'LinuxTargetVM'
    runOptions: 'commands'
    commands: 'ls -al'